# Generated by Django 5.0.1 on 2024-01-16 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Financeforge", "0002_remove_blogpost_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
